# Datenanalyse - R Basis 
*Erwerbe R Basiskompetenzen am Beispiel von regionalen Daten aus OWL*

Schön das Du wieder dabei bist! In diesem ersten Jupyter Notebook aus dem Kurs *„Von der Datenanalyse zur Datengeschichte“* wollen wir Dir anhand von offen regionalen Datensätzen der *Stadt Bielefeld* und aus der Region *Ostwestfalen-Lippe (OWL)* zunächst einmal einige Basiskenntnisse für die Datenanalyse in R vermitteln, die Du später benötigen wirst.

## Wie können wir Daten in R verarbeiten?

Stell Dir vor wir möchten die Einwohnerzahlen der 6 größten Städte in Ostwestfalen in R speichern. Hierzu definieren für jede Stadt ein Variable der wir die Einwohnerzahl als Wert zuweisen

In [1]:

Bi <- 334195
Mi <- 12

Wenn Du nun den Namen der Variable eingibst erhälst Du die Einwohnerzahl als Output.

In [7]:
Bi

[1] 334195

## *Jetzt probier Du es doch einmal: Definiere Variablen für die 5 anderen Städte*

In [1]:
Dt <- 74254
Gt <- 100861
Hf <- 66638
Mi <- 81716
Pb <- 151633

In [4]:
Hf <- 66638

In [4]:
Hf

[1] 66638

# Bevölkerungsdaten Stadt Bielefeld gesamt
 https://open-data.bielefeld.de/dataset/alters-und-geschlechtsstruktur-2018-2020

In [3]:
# Bevölkerungsdaten Bielfeld als Dataframe einlesen
data_Bv_Bi <- read.csv(url("https://open-data.bielefeld.de/sites/default/files/Alters_und_Geschlechtsstruktur2018bis2020ges_0.csv"), header = TRUE, sep = ';')

In [4]:
data_Bv_Bi

    Jahr Bielefeld           Geschlecht Altersstufe
1   2020 Bielefeld insgesamt maennlich  0
2   2020 Bielefeld insgesamt maennlich  1
3   2020 Bielefeld insgesamt maennlich  2
4   2020 Bielefeld insgesamt maennlich  3
5   2020 Bielefeld insgesamt maennlich  4
6   2020 Bielefeld insgesamt maennlich  5
7   2020 Bielefeld insgesamt maennlich  6
8   2020 Bielefeld insgesamt maennlich  7
9   2020 Bielefeld insgesamt maennlich  8
10  2020 Bielefeld insgesamt maennlich  9
11  2020 Bielefeld insgesamt maennlich  10
12  2020 Bielefeld insgesamt maennlich  11
13  2020 Bielefeld insgesamt maennlich  12
14  2020 Bielefeld insgesamt maennlich  13
15  2020 Bielefeld insgesamt maennlich  14
16  2020 Bielefeld insgesamt maennlich  15
17  2020 Bielefeld insgesamt maennlich  16
18  2020 Bielefeld insgesamt maennlich  17
19  2020 Bielefeld insgesamt maennlich  18
20  2020 Bielefeld insgesamt maennlich  19
21  2020 Bielefeld insgesamt maennlich  20
22  2020 Bielefeld insgesamt maennlich  21
23  2020 Bielefeld insgesamt maennlich  22
24  2020 Bielefeld insgesamt maennlich  23
25  2020 Bielefeld insgesamt maennlich  24
26  2020 Bielefeld insgesamt maennlich  25
27  2020 Bielefeld insgesamt maennlich  26
28  2020 Bielefeld insgesamt maennlich  27
29  2020 Bielefeld insgesamt maennlich  28
30  2020 Bielefeld insgesamt maennlich  29
... ...  ...                 ...        ...
517 2018 Bielefeld insgesamt weiblich   61
518 2018 Bielefeld insgesamt weiblich   62
519 2018 Bielefeld insgesamt weiblich   63
520 2018 Bielefeld insgesamt weiblich   64
521 2018 Bielefeld insgesamt weiblich   65
522 2018 Bielefeld insgesamt weiblich   66
523 2018 Bielefeld insgesamt weiblich   67
524 2018 Bielefeld insgesamt weiblich   68
525 2018 Bielefeld insgesamt weiblich   69
526 2018 Bielefeld insgesamt weiblich   70
527 2018 Bielefeld insgesamt weiblich   71
528 2018 Bielefeld insgesamt weiblich   72
529 2018 Bielefeld insgesamt weiblich   73
530 2018 Bielefeld insgesamt weiblich   74
531 2018 Bielefeld insgesamt weiblich   75
532 2018 Bielefeld insgesamt weiblich   76
533 2018 Bielefeld insgesamt weiblich   77
534 2018 Bielefeld insgesamt weiblich   78
535 2018 Bielefeld insgesamt weiblich   79
536 2018 Bielefeld insgesamt weiblich   80
537 2018 Bielefeld insgesamt weiblich   81
538 2018 Bielefeld insgesamt weiblich   82
539 2018 Bielefeld insgesamt weiblich   83
540 2018 Bielefeld insgesamt weiblich   84
541 2018 Bielefeld insgesamt weiblich   85
542 2018 Bielefeld insgesamt weiblich   86
543 2018 Bielefeld insgesamt weiblich   87
544 2018 Bielefeld insgesamt weiblich   88
545 2018 Bielefeld insgesamt weiblich   89
546 2018 Bielefeld insgesamt weiblich   90_und_aelter
    Einwohner_innen.am.Ort.der.Hauptwohnung
1   1661
2   1764
3   1695
4   1700
5   1647
6   1649
7   1605
8   1598
9   1542
10  1618
11  1633
12  1525
13  1649
14  1621
15  1639
16  1635
17  1713
18  1660
19  1788
20  1785
21  2069
22  2074
23  2243
24  2497
25  2497
26  2408
27  2533
28  2597
29  2591
30  2655
... ...
517 2121
518 2091
519 2060
520 2020
521 1853
522 1805
523 1734
524 1785
525 1763
526 1582
527 1461
528 1291
529 1210
530 1470
531 1448
532 1391
533 1756
534 1888
535 1915
536 1654
537 1633
538 1451
539 1379
540 1250
541  928
542  847
543  827
544  802
545  680
546 2660

Nach dem wir uns nun den Dataframe angeschaut haben intressiert uns eigentlich nur das Jahr 2020! Hier für können wir den *subset* Befehl verwenden:

In [5]:
data_Bv_Bi_2020 <- subset(data_Bv_Bi, Jahr = 2020)

In [6]:
data_Bv_Bi_2020

    Jahr Bielefeld           Geschlecht Altersstufe
1   2020 Bielefeld insgesamt maennlich  0
2   2020 Bielefeld insgesamt maennlich  1
3   2020 Bielefeld insgesamt maennlich  2
4   2020 Bielefeld insgesamt maennlich  3
5   2020 Bielefeld insgesamt maennlich  4
6   2020 Bielefeld insgesamt maennlich  5
7   2020 Bielefeld insgesamt maennlich  6
8   2020 Bielefeld insgesamt maennlich  7
9   2020 Bielefeld insgesamt maennlich  8
10  2020 Bielefeld insgesamt maennlich  9
11  2020 Bielefeld insgesamt maennlich  10
12  2020 Bielefeld insgesamt maennlich  11
13  2020 Bielefeld insgesamt maennlich  12
14  2020 Bielefeld insgesamt maennlich  13
15  2020 Bielefeld insgesamt maennlich  14
16  2020 Bielefeld insgesamt maennlich  15
17  2020 Bielefeld insgesamt maennlich  16
18  2020 Bielefeld insgesamt maennlich  17
19  2020 Bielefeld insgesamt maennlich  18
20  2020 Bielefeld insgesamt maennlich  19
21  2020 Bielefeld insgesamt maennlich  20
22  2020 Bielefeld insgesamt maennlich  21
23  2020 Bielefeld insgesamt maennlich  22
24  2020 Bielefeld insgesamt maennlich  23
25  2020 Bielefeld insgesamt maennlich  24
26  2020 Bielefeld insgesamt maennlich  25
27  2020 Bielefeld insgesamt maennlich  26
28  2020 Bielefeld insgesamt maennlich  27
29  2020 Bielefeld insgesamt maennlich  28
30  2020 Bielefeld insgesamt maennlich  29
... ...  ...                 ...        ...
517 2018 Bielefeld insgesamt weiblich   61
518 2018 Bielefeld insgesamt weiblich   62
519 2018 Bielefeld insgesamt weiblich   63
520 2018 Bielefeld insgesamt weiblich   64
521 2018 Bielefeld insgesamt weiblich   65
522 2018 Bielefeld insgesamt weiblich   66
523 2018 Bielefeld insgesamt weiblich   67
524 2018 Bielefeld insgesamt weiblich   68
525 2018 Bielefeld insgesamt weiblich   69
526 2018 Bielefeld insgesamt weiblich   70
527 2018 Bielefeld insgesamt weiblich   71
528 2018 Bielefeld insgesamt weiblich   72
529 2018 Bielefeld insgesamt weiblich   73
530 2018 Bielefeld insgesamt weiblich   74
531 2018 Bielefeld insgesamt weiblich   75
532 2018 Bielefeld insgesamt weiblich   76
533 2018 Bielefeld insgesamt weiblich   77
534 2018 Bielefeld insgesamt weiblich   78
535 2018 Bielefeld insgesamt weiblich   79
536 2018 Bielefeld insgesamt weiblich   80
537 2018 Bielefeld insgesamt weiblich   81
538 2018 Bielefeld insgesamt weiblich   82
539 2018 Bielefeld insgesamt weiblich   83
540 2018 Bielefeld insgesamt weiblich   84
541 2018 Bielefeld insgesamt weiblich   85
542 2018 Bielefeld insgesamt weiblich   86
543 2018 Bielefeld insgesamt weiblich   87
544 2018 Bielefeld insgesamt weiblich   88
545 2018 Bielefeld insgesamt weiblich   89
546 2018 Bielefeld insgesamt weiblich   90_und_aelter
    Einwohner_innen.am.Ort.der.Hauptwohnung
1   1661
2   1764
3   1695
4   1700
5   1647
6   1649
7   1605
8   1598
9   1542
10  1618
11  1633
12  1525
13  1649
14  1621
15  1639
16  1635
17  1713
18  1660
19  1788
20  1785
21  2069
22  2074
23  2243
24  2497
25  2497
26  2408
27  2533
28  2597
29  2591
30  2655
... ...
517 2121
518 2091
519 2060
520 2020
521 1853
522 1805
523 1734
524 1785
525 1763
526 1582
527 1461
528 1291
529 1210
530 1470
531 1448
532 1391
533 1756
534 1888
535 1915
536 1654
537 1633
538 1451
539 1379
540 1250
541  928
542  847
543  827
544  802
545  680
546 2660